"""
Constants used throughout the blind navigation application.
"""

# Class blacklist - add classes you want to filter out
BLACKLISTED_CLASSES = {
    'house',
    'office building',
    'building',
    'skyscraper',
    'tower',
    # Note: Clothing items removed from blacklist - they're valid detections
    # Face/person deduplication is handled by spatial overlap logic instead
}

# Class mapping - combine similar classes into one
CLASS_MAPPING = {
    # All human-related classes map to "person"
    'man': 'person',
    'woman': 'person',
    'boy': 'person',
    'girl': 'person',
    'human face': 'person',
    'face': 'person',
    'head': 'person',
    'human': 'person',
    # Add more mappings as needed
}

# Detection thresholds
DEFAULT_CONFIDENCE_THRESHOLD = 0.30
DEFAULT_IOU_THRESHOLD = 0.65
MAX_DETECTIONS = 50

# Tracking parameters
TRACK_HISTORY_LENGTH = 30  # Number of positions to keep in trajectory
MAX_TRACKER_AGE = 10  # Max frames to keep alive a track without detections (reduced from 30 to prevent false matches)
MIN_TRACK_INIT = 2  # Number of consecutive detections before track is confirmed (reduced from 3 for faster initialization)
NMS_MAX_OVERLAP = 0.7  # Non-max suppression overlap threshold
MAX_COSINE_DISTANCE = 0.25  # Cosine distance threshold for matching (reduced from 0.4 to be more strict on appearance)
NN_BUDGET = 100  # Maximum size of appearance descriptor gallery
USE_VISUAL_EMBEDDINGS = True  # Revert to True - embedder=None not supported by deep_sort_realtime

# Selective tracking optimization - only track objects that need collision analysis
ENABLE_SELECTIVE_TRACKING = True  # Only track moving/approaching objects for performance
SELECTIVE_TRACKING_CLASSES = {'person', 'car', 'bicycle', 'motorcycle', 'truck', 'bus', 'dog', 'cat'}  # Always track these
SELECTIVE_TRACKING_MIN_SIZE = 0.03  # Track objects > 3% of frame area (ignore tiny/far objects)

# Collision detection
USER_ZONE_RADIUS_FACTOR = 0.15  # 15% of frame size
COLLISION_PREDICTION_FRAMES = 10  # How many frames ahead to predict
STATIONARY_THRESHOLD = 5  # Pixels displacement threshold

# Speed classification
SPEED_SLOW_THRESHOLD = 2.0  # pixels per frame
SPEED_MEDIUM_THRESHOLD = 10.0  # pixels per frame

# Pathfinding
DEFAULT_GRID_SIZE = 20  # pixels per grid cell
OBSTACLE_DILATION_ITERATIONS = 1  # Safety margin around obstacles
PATH_SAFETY_CHECK_RADIUS = 3  # Grid cells to check around path

# Image processing
MAX_IMAGE_DIMENSION = 640  # Resize larger images for faster inference
ROTATION_DETECTION_THRESHOLD = 0.75  # Aspect ratio threshold for rotation detection
ROTATION_TEST_SIZE = (320, 240)  # Size for quick rotation detection test

# Depth estimation
DEPTH_INFERENCE_INTERVAL = 10  # Run depth estimation every N frames for performance (increased from 3 for speed)
DEPTH_MODEL_TYPE = 'depth-anything-v2-small'  # Model type: 'midas' or 'depth-anything-v2-small'
DEPTH_INPUT_SIZE = 256  # Resize input to this size for faster inference (was 384)
DEPTH_CACHE_FRAMES = 10  # Number of frames to cache depth maps
DEPTH_FALLBACK_ENABLED = True  # Use pinhole camera model fallback when depth unavailable
DEPTH_ASYNC_ENABLED = True  # Run depth estimation in background thread (non-blocking)
DEPTH_AUTO_CALIBRATION = True  # Auto-calibrate depth scale using pinhole estimates
DEPTH_USE_FP16 = True  # Enable FP16 mixed precision for 2x faster inference on RTX GPUs (NEW: 2025-10-19)

# Camera calibration (pinhole model)
DEFAULT_FOCAL_LENGTH = 500  # pixels - rough estimate for typical mobile camera

# Comprehensive object heights database (in meters) - 500+ OIV7 classes
# Heights represent typical real-world measurements for each object
KNOWN_OBJECT_HEIGHTS = {
    # Musical Instruments
    'accordion': 0.4,
    'banjo': 0.9,
    'cello': 1.2,
    'drum': 0.5,
    'flute': 0.6,
    'french horn': 0.4,
    'guitar': 1.0,
    'harmonica': 0.1,
    'harp': 1.8,
    'harpsichord': 1.0,
    'musical keyboard': 0.15,
    'oboe': 0.65,
    'organ (musical instrument)': 2.5,
    'piano': 1.2,
    'saxophone': 0.7,
    'trombone': 0.9,
    'trumpet': 0.5,
    'violin': 0.6,

    # Office & Stationery
    'adhesive tape': 0.05,
    'computer keyboard': 0.02,
    'computer monitor': 0.5,
    'computer mouse': 0.04,
    'office supplies': 0.2,
    'pen': 0.15,
    'pencil case': 0.08,
    'pencil sharpener': 0.05,
    'printer': 0.4,
    'ring binder': 0.3,
    'ruler': 0.3,
    'stapler': 0.1,

    # Vehicles
    'aircraft': 15.0,
    'airplane': 15.0,
    'ambulance': 2.5,
    'barge': 5.0,
    'boat': 3.0,
    'bus': 3.0,
    'car': 1.5,
    'golf cart': 1.8,
    'gondola': 1.5,
    'helicopter': 3.0,
    'jet ski': 1.2,
    'land vehicle': 1.5,
    'limousine': 1.5,
    'motorcycle': 1.2,
    'taxi': 1.5,
    'train': 4.0,
    'truck': 2.5,
    'van': 2.0,
    'vehicle': 1.5,

    # Animals - Mammals
    'alpaca': 1.0,
    'animal': 0.8,
    'armadillo': 0.3,
    'bat (animal)': 0.15,
    'bear': 1.5,
    'brown bear': 1.5,
    'bull': 1.5,
    'camel': 2.0,
    'carnivore': 0.8,
    'cat': 0.3,
    'cattle': 1.5,
    'cheetah': 0.9,
    'cow': 1.5,
    'crocodile': 0.5,
    'deer': 1.2,
    'dog': 0.6,
    'dolphin': 0.8,
    'elephant': 3.0,
    'fox': 0.4,
    'giraffe': 5.0,
    'goat': 0.9,
    'hamster': 0.1,
    'harbor seal': 0.6,
    'hedgehog': 0.15,
    'hippopotamus': 1.5,
    'horse': 1.6,
    'jaguar (animal)': 0.8,
    'kangaroo': 1.5,
    'koala': 0.7,
    'leopard': 0.7,
    'lion': 1.2,
    'lynx': 0.6,
    'mammal': 0.8,
    'monkey': 0.5,
    'mule': 1.4,
    'ostrich': 2.0,
    'otter': 0.3,
    'panda': 0.9,
    'pig': 0.6,
    'polar bear': 1.5,
    'porcupine': 0.4,
    'rabbit': 0.3,
    'raccoon': 0.3,
    'red panda': 0.6,
    'rhinoceros': 1.5,
    'sea lion': 1.0,
    'sheep': 0.9,
    'skunk': 0.3,
    'squirrel': 0.2,
    'tiger': 1.0,
    'whale': 5.0,
    'zebra': 1.4,

    # Animals - Birds
    'bee': 0.02,
    'bird': 0.3,
    'blue jay': 0.3,
    'canary': 0.15,
    'duck': 0.4,
    'eagle': 0.8,
    'falcon': 0.5,
    'goose': 0.8,
    'magpie': 0.4,
    'owl': 0.5,
    'parrot': 0.4,
    'penguin': 0.7,
    'raven': 0.5,
    'sparrow': 0.15,
    'swan': 1.0,
    'turkey': 1.0,
    'woodpecker': 0.25,

    # Animals - Insects & Small Creatures
    'ant': 0.01,
    'beetle': 0.02,
    'butterfly': 0.05,
    'caterpillar': 0.05,
    'centipede': 0.02,
    'crab': 0.15,
    'dragonfly': 0.08,
    'insect': 0.02,
    'invertebrate': 0.05,
    'isopod': 0.02,
    'ladybug': 0.01,
    'scorpion': 0.1,
    'snail': 0.05,
    'snake': 0.1,
    'spider': 0.05,
    'starfish': 0.1,
    'tick': 0.01,
    'worm': 0.02,

    # Food - Fruits & Vegetables
    'apple': 0.08,
    'artichoke': 0.15,
    'banana': 0.2,
    'bell pepper': 0.12,
    'broccoli': 0.2,
    'cabbage': 0.2,
    'cantaloupe': 0.2,
    'carrot': 0.25,
    'cheese': 0.1,
    'coconut': 0.25,
    'common fig': 0.08,
    'common sunflower': 2.0,
    'cucumber': 0.3,
    'garden asparagus': 0.25,
    'grape': 0.02,
    'grapefruit': 0.12,
    'lemon': 0.08,
    'mango': 0.12,
    'mushroom': 0.15,
    'orange': 0.08,
    'peach': 0.08,
    'pear': 0.1,
    'pineapple': 0.3,
    'pomegranate': 0.1,
    'potato': 0.08,
    'pumpkin': 0.3,
    'radish': 0.05,
    'strawberry': 0.04,
    'tomato': 0.08,
    'vegetable': 0.15,
    'watermelon': 0.3,
    'zucchini': 0.25,

    # Food - Prepared
    'bagel': 0.1,
    'baked goods': 0.15,
    'beer': 0.3,
    'bowl': 0.1,
    'bread': 0.15,
    'burrito': 0.15,
    'cake': 0.2,
    'cocktail': 0.15,
    'coffee': 0.1,
    'coffee cup': 0.1,
    'cookie': 0.1,
    'croissant': 0.1,
    'dessert': 0.15,
    'doughnut': 0.08,
    'drink': 0.25,
    'fast food': 0.15,
    'food': 0.2,
    'french fries': 0.1,
    'guacamole': 0.1,
    'hamburger': 0.12,
    'hot dog': 0.15,
    'ice cream': 0.15,
    'juice': 0.25,
    'milk': 0.25,
    'muffin': 0.1,
    'pancake': 0.05,
    'pasta': 0.05,
    'pastry': 0.1,
    'pizza': 0.05,
    'popcorn': 0.2,
    'pretzel': 0.1,
    'salad': 0.15,
    'sandwich': 0.12,
    'snack': 0.15,
    'sushi': 0.05,
    'taco': 0.12,
    'waffle': 0.05,

    # Furniture
    'bed': 0.6,
    'bench': 0.5,
    'cabinetry': 1.5,
    'cat furniture': 0.8,
    'chair': 1.0,
    'chest of drawers': 1.2,
    'closet': 2.0,
    'coffee table': 0.5,
    'couch': 0.9,
    'cupboard': 1.8,
    'desk': 0.75,
    'dog bed': 0.3,
    'filing cabinet': 1.3,
    'furniture': 1.0,
    'infant bed': 0.8,
    'kitchen & dining room table': 0.75,
    'loveseat': 0.9,
    'nightstand': 0.6,
    'shelf': 1.5,
    'sofa bed': 0.9,
    'stool': 0.5,
    'studio couch': 0.9,
    'table': 0.75,
    'wardrobe': 2.0,

    # Household Items
    'auto part': 0.3,
    'axe': 0.8,
    'band-aid': 0.1,
    'bathtub': 0.6,
    'beaker': 0.2,
    'belt': 0.05,
    'bidet': 0.5,
    'binoculars': 0.15,
    'blender': 0.4,
    'book': 0.25,
    'bookcase': 1.8,
    'boot': 0.4,
    'bottle': 0.25,
    'bottle opener': 0.1,
    'bow and arrow': 1.2,
    'bowling equipment': 0.3,
    'box': 0.4,
    'briefcase': 0.4,
    'calculator': 0.15,
    'camera': 0.15,
    'can opener': 0.15,
    'candle': 0.2,
    'candy': 0.05,

    # Kitchen & Dining
    'cake stand': 0.3,
    'chopsticks': 0.25,
    'cocktail shaker': 0.25,
    'coffeemaker': 0.35,
    'container': 0.2,
    'countertop': 0.9,
    'cutting board': 0.02,
    'dishwasher': 0.85,
    'food processor': 0.4,
    'fork': 0.2,
    'frying pan': 0.05,
    'gas stove': 0.9,
    'kettle': 0.25,
    'kitchen appliance': 0.4,
    'kitchen knife': 0.3,
    'kitchen utensil': 0.25,
    'kitchenware': 0.2,
    'knife': 0.25,
    'ladle': 0.3,
    'measuring cup': 0.15,
    'microwave oven': 0.35,
    'mixer': 0.35,
    'mixing bowl': 0.15,
    'mug': 0.1,
    'oven': 0.9,
    'pitcher (container)': 0.25,
    'pizza cutter': 0.2,
    'plate': 0.03,
    'platter': 0.05,
    'pressure cooker': 0.3,
    'refrigerator': 1.8,
    'salt and pepper shakers': 0.1,
    'saucer': 0.02,
    'serving tray': 0.05,
    'sink': 0.25,
    'slow cooker': 0.3,
    'spatula': 0.3,
    'spice rack': 0.4,
    'spoon': 0.18,
    'tableware': 0.1,
    'tap': 0.15,
    'teapot': 0.2,
    'tin can': 0.15,
    'toaster': 0.25,
    'wok': 0.15,
    'wine glass': 0.2,
    'wine rack': 0.5,

    # Clothing & Accessories
    'backpack': 0.5,
    'bicycle helmet': 0.25,
    'brassiere': 0.15,
    'clothing': 0.7,
    'coat': 1.0,
    'cowboy hat': 0.15,
    'earrings': 0.05,
    'fashion accessory': 0.2,
    'fedora': 0.15,
    'footwear': 0.3,
    'glove': 0.25,
    'goggles': 0.1,
    'handbag': 0.3,
    'hat': 0.15,
    'high heels': 0.15,
    'jacket': 0.7,
    'jeans': 1.0,
    'luggage and bags': 0.6,
    'miniskirt': 0.4,
    'necklace': 0.3,
    'sandal': 0.05,
    'scarf': 1.5,
    'shirt': 0.7,
    'shorts': 0.4,
    'skirt': 0.6,
    'sock': 0.3,
    'sombrero': 0.4,
    'suit': 1.5,
    'suitcase': 0.7,
    'sun hat': 0.15,
    'sunglasses': 0.06,
    'tie': 1.4,
    'trousers': 1.0,
    'umbrella': 0.9,

    # Sports & Recreation
    'balance beam': 1.2,
    'ball': 0.22,
    'balloon': 0.3,
    'baseball bat': 1.0,
    'baseball glove': 0.3,
    'bicycle': 1.0,
    'bicycle wheel': 0.7,
    'cricket ball': 0.07,
    'dumbbell': 0.3,
    'flying disc': 0.03,
    'football': 0.28,
    'football helmet': 0.25,
    'golf ball': 0.04,
    'hiking equipment': 0.5,
    'horizontal bar': 2.5,
    'kite': 1.0,
    'paddle': 1.5,
    'punching bag': 1.2,
    'racket': 0.7,
    'rugby ball': 0.3,
    'skateboard': 0.12,
    'ski': 1.7,
    'snowboard': 1.5,
    'sports ball': 0.22,
    'sports equipment': 0.5,
    'surfboard': 2.0,
    'table tennis racket': 0.26,
    'tennis ball': 0.07,
    'tennis racket': 0.7,
    'volleyball (ball)': 0.21,

    # Electronics & Technology
    'digital clock': 0.15,
    'headphones': 0.2,
    'ipod': 0.1,
    'laptop': 0.02,
    'microphone': 0.25,
    'mobile phone': 0.15,
    'remote control': 0.15,
    'tablet computer': 0.01,
    'telephone': 0.25,
    'television': 0.7,
    'wall clock': 0.3,
    'watch': 0.05,

    # Home Appliances
    'ceiling fan': 0.4,
    'hair dryer': 0.25,
    'hair spray': 0.2,
    'hand dryer': 0.3,
    'heater': 0.6,
    'home appliance': 0.5,
    'humidifier': 0.4,
    'mechanical fan': 0.5,
    'sewing machine': 0.35,
    'washing machine': 1.0,
    'wood-burning stove': 1.0,

    # Tools & Equipment
    'cannon': 1.5,
    'chainsaw': 0.5,
    'chisel': 0.25,
    'dagger': 0.3,
    'drill (tool)': 0.3,
    'hammer': 0.35,
    'ladder': 2.0,
    'nail (construction)': 0.05,
    'paper cutter': 0.4,
    'ratchet (device)': 0.25,
    'scissors': 0.2,
    'screwdriver': 0.25,
    'tool': 0.3,
    'tripod': 1.5,
    'whisk': 0.25,
    'wrench': 0.25,

    # Buildings & Structures
    'billboard': 5.0,
    'building': 10.0,
    'castle': 15.0,
    'convenience store': 5.0,
    'door': 2.0,
    'fireplace': 1.5,
    'house': 8.0,
    'lighthouse': 20.0,
    'office building': 15.0,
    'porch': 3.0,
    'skyscraper': 50.0,
    'tower': 20.0,
    'tree house': 4.0,
    'window': 1.5,
    'window blind': 1.5,

    # Bathroom & Personal Care
    'bathroom accessory': 0.15,
    'bathroom cabinet': 0.8,
    'cosmetics': 0.1,
    'diaper': 0.05,
    'face powder': 0.08,
    'facial tissue holder': 0.12,
    'lipstick': 0.08,
    'medical equipment': 0.5,
    'perfume': 0.15,
    'person': 1.7,
    'personal care': 0.2,
    'personal flotation device': 0.5,
    'pillow': 0.15,
    'plumbing fixture': 0.5,
    'shower': 2.0,
    'soap dispenser': 0.2,
    'stethoscope': 0.7,
    'syringe': 0.15,
    'toilet': 0.75,
    'toilet paper': 0.12,
    'toothbrush': 0.2,
    'towel': 0.7,

    # Human Body Parts
    'boy': 1.4,
    'girl': 1.4,
    'human arm': 0.7,
    'human beard': 0.15,
    'human body': 1.7,
    'human ear': 0.08,
    'human eye': 0.03,
    'human face': 0.25,
    'human foot': 0.28,
    'human hair': 0.3,
    'human hand': 0.2,
    'human head': 0.25,
    'human leg': 0.9,
    'human mouth': 0.08,
    'human nose': 0.05,
    'man': 1.75,
    'woman': 1.65,

    # Plants & Nature
    'beehive': 0.4,
    'flower': 0.3,
    'flowerpot': 0.3,
    'honeycomb': 0.3,
    'houseplant': 0.5,
    'lavender (plant)': 0.6,
    'lily': 0.6,
    'maple': 10.0,
    'palm tree': 8.0,
    'plant': 0.5,
    'potted plant': 0.5,
    'rose': 0.8,
    'tree': 10.0,
    'willow': 12.0,

    # Outdoor & Urban
    'fire hydrant': 0.9,
    'fountain': 2.0,
    'parking meter': 1.5,
    'stairs': 3.0,
    'stop sign': 2.0,
    'street light': 5.0,
    'stretcher': 0.5,
    'swimming pool': 1.5,
    'traffic light': 2.5,
    'traffic sign': 1.5,

    # Toys & Games
    'crown': 0.15,
    'dice': 0.02,
    'doll': 0.4,
    'picnic basket': 0.3,
    'poster': 0.6,
    'teddy bear': 0.4,
    'tent': 2.0,
    'toy': 0.3,

    # Weapons
    'bomb': 0.3,
    'handgun': 0.2,
    'missile': 5.0,
    'rifle': 1.0,
    'shotgun': 1.2,
    'sword': 1.0,
    'weapon': 0.8,

    # Miscellaneous Objects
    'alarm clock': 0.15,
    'barrel': 0.9,
    'billiard table': 0.8,
    'bronze sculpture': 1.5,
    'bust': 0.5,
    'coin': 0.02,
    'crutch': 1.4,
    'curtain': 2.0,
    'dinosaur': 3.0,
    'door handle': 0.1,
    'drawer': 0.3,
    'drinking straw': 0.2,
    'envelope': 0.01,
    'eraser': 0.03,
    'fax': 0.4,
    'flag': 1.5,
    'flashlight': 0.2,
    'indoor rower': 1.0,
    'jacuzzi': 0.8,
    'lamp': 0.5,
    'lantern': 0.3,
    'light bulb': 0.12,
    'light switch': 0.1,
    'mirror': 0.6,
    'paper towel': 0.28,
    'parachute': 1.0,
    'picture frame': 0.4,
    'plastic bag': 0.5,
    'sculpture': 1.5,
    'seat belt': 1.0,
    'segway': 1.3,
    'skull': 0.25,
    'snowman': 1.5,
    'snowmobile': 1.2,
    'snowplow': 2.5,
    'stationary bicycle': 1.2,
    'submarine': 8.0,
    'submarine sandwich': 0.3,
    'swim cap': 0.02,
    'swimwear': 0.3,
    'tart': 0.05,
    'tiara': 0.1,
    'tire': 0.7,
    'torch': 0.3,
    'treadmill': 1.4,
    'training bench': 0.5,
    'unicycle': 1.5,
    'vehicle registration plate': 0.15,
    'waffle iron': 0.15,
    'waste container': 0.8,
    'watercraft': 3.0,
    'wheel': 0.7,
    'wheelchair': 1.2,
    'whiteboard': 1.2,

    # Seafood & Marine Life
    'jellyfish': 0.3,
    'lobster': 0.3,
    'marine invertebrates': 0.2,
    'marine mammal': 2.0,
    'oyster': 0.1,
    'rays and skates': 0.5,
    'sea turtle': 0.8,
    'seafood': 0.2,
    'seahorse': 0.15,
    'shark': 2.0,
    'shellfish': 0.15,
    'shrimp': 0.1,
    'squid': 0.5,
    'tortoise': 0.3,
    'turtle': 0.3,
}
# Total: 500+ object classes with realistic height estimates
